### ISSUE TITLE
Typo in Security Server Windows Auth Sample Doc

### ISSUE THREAD

**Issue by ioplex** [spring-projects/spring-security-kerberos#278]
Disclaimer: I have very little knowledge of Spring

Running:

`$ java -jar sec-server-win-auth-2.1.1.jar --spring.config.location=sec-server-win-auth.yaml`

with sec-server-win-auth.yaml contents of:

```
server:
    port: 8080
    app:
        ad-domain: EXAMPLE.ORG
        ad-server: ldap://WIN-EKBO0EQ7TS7.example.org/
        service-principal: HTTP/neo.example.org@EXAMPLE.ORG
        keytab-location: /tmp/tomcat.keytab
        ldap-search-base: dc=example,dc=org
        ldap-search-filter: "(| (userPrincipalName={0}) (sAMAccountName={0}))"

```
with values substituted appropriately of course, yields the following error:

```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'app.ad-domain' in value "${app.ad-domain}"
	at org.springframework.util.PropertyPlaceholderHel..
```
Changing the yaml, by removing some leading spaces, to:

```
server:
    port: 8080
app:
    ad-domain: EXAMPLE.ORG
    ad-server: ldap://WIN-EKBO0EQ7TS7.example.org/
    service-principal: HTTP/neo.example.org@EXAMPLE.ORG
    keytab-location: /tmp/tomcat.keytab
    ldap-search-base: dc=example,dc=org
    ldap-search-filter: "(| (userPrincipalName={0}) (sAMAccountName={0}))"
```
appears to fix the issue.

From looking at the other configs, this appears to be a typo in the documentation?
